config/routes.rb
Rails.application.routes.draw do
  root "events#index"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "register", to: "users#new"

  resources :users do
    scope module: :users do
      resources :events
    end
  end
  resources :orders, only: [:index, :show]

  resources :events, except: :destroy do
    resources :orders, only: [:create, :new]
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :creator, class_name: "User"
  belongs_to :venue
  belongs_to :category

  has_many :ticket_types, -> { order(price: :desc) }, dependent: :destroy
  has_many :orders

  validates :name, :creator, :extended_html_description, :venue, :category, :starts_at, presence: true
  validates :name, uniqueness: { scope: [:venue_id, :starts_at] }

  scope :upcoming, -> { where('starts_at > ?', Time.current).order(:starts_at) }

  delegate :name, to: :category, prefix: true
  delegate :region_name, to: :venue

  def starts_at_to_s
    starts_at.strftime(FULL_DATE_FORMAT)
  end

  def starts_at_to_month
    starts_at.strftime(FULL_MONTH_FORMAT)
  end

  def starts_at_to_day
    starts_at.strftime(DAY_FORMAT)
  end

  def min_price
    ticket_types.minimum(:price)
  end

  def has_expired?
    starts_at < Time.current
  end

  def self.search(keyword)
    keywords = keyword.downcase.split.join("|")
    upcoming.where("LOWER(name) SIMILAR TO '%(#{keywords})%'")
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @keyword = params["search"]
    @events = (@keyword.present? ? Event.search(@keyword) : Event.upcoming).includes(:venue, :category)
  end

  def show
    @event = Event.find(params[:id])
  end
end

app/controllers/users/events_controller.rb
class Users::EventsController < ApplicationController
  layout "settings"

  before_action :load_user

  def index
    authorize! :view_events_of, @user
    @events = current_user.events.includes(:venue)
  end

  private

  def load_user
    @user = User.new(id: params[:user_id])
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def header_background_image_path
    "/images/cover/home-search-bg-0#{rand(6)}.jpg"
  end
end

app/views/events/_card.html.slim
.col-md-6
  = link_to event_path(event) do
    .card
      .cover
        .cover-content
          = image_tag(event.hero_image_url)
      .card-block
        h4.card-title
          = event.name
        .card-text
          .col-sm-9
            .min-price
              | From 
              span.price
                = formatted_price(event.min_price)
            p.details
              span.region
                = event.region_name
              = fa_icon "hashtag"
              span.category
                = event.category_name
          .col-sm-3
            .icon-calendar
              .month-wrap
                = event.starts_at_to_month
              .days-wrap
                = event.starts_at_to_day

app/views/events/index.html.slim
.events-header style=("background-image: url(#{header_background_image_path})")
  .container
    h2
      |  Discover upcoming events 
    form
      input.form-control type="text" name="search" placeholder="Search for events, shows, courses..." value="#{@keyword}" onfocus="this.value = this.value;" autofocus="true"
.container-fluid.events-list
  - if (message = flash[:alert]).present?
    .alert.alert-danger
      = message
  - if @events.empty?
    p.no-results
      | No events found!
  - else
    - @events.in_groups_of(2, false) do |group|
      .row
        - group.each do |event|
          = render partial: "card", locals: { event: event }

app/views/events/show.html.slim
.container-fluid.no-pad.events-detail
  .row.no-pad
    .col-md-3.sidebar
      p
        = fa_icon "ticket"
        |  Price 
      h1
        |  Hot Events 
      .ticket-list
        - @event.ticket_types.each do |ticket_type|
          .row
            .col-md-6.ticket-name
              = ticket_type.name
            .col-md-6.price.text-right
              = formatted_price(ticket_type.price)
          .clearfix
        = link_to new_event_order_path(@event) do
          button.btn.btn-lg.btn-block.btn-danger.book-now-button class=("disabled" if @event.has_expired?)
            |  BOOK NOW 
    .col-md-9.event-content
      .hero-img.hidden-sm-down style=("background-image: url(#{@event.hero_image_url}); background-size: cover")
      .container
        h3
          = @event.name
        .pull-left
          = fa_icon "clock-o"
        .time-details
          = @event.starts_at_to_s
        .pull-left
          = fa_icon "map-marker"
        .venue-details
          = @event.venue.name
          br
          = @event.venue.full_address
        .img-spacer
          = image_tag "shadow-top.png"
        .extended-description
          = @event.extended_html_description.html_safe