config/routes.rb
Rails.application.routes.draw do
  root "events#index"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "register", to: "users#new"

  resources :users do
    scope module: :users do
      resources :events
    end
  end
  resources :orders, only: [:index, :show]

  resources :events, except: :destroy do
    resources :orders, only: [:create, :new]
  end

end

app/views/layouts/_form_errors.html.slim
- if session[:previous_url]
  p.error Please login first!
- errors.full_messages.each do |msg|
  p.error= msg

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Cheetah Ticket
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-fixed-top.navbar-dark.bg-inverse
      = link_to "Cheetah Ticket", root_path, class: "navbar-brand"
      - if current_user
        ul.nav.navbar-nav.navbar-right
          li.nav-item
            = link_to "Welcome #{current_user.email}", orders_path, class: "nav-link"
          li.nav-item
            = link_to "Sign Out", logout_path, method: :delete, class: "nav-link"
      - else
        ul.nav.navbar-nav
          li.nav-item
            = link_to "Sign In", login_path, class: "nav-link"
          li.nav-item
            = link_to "Sign Up", register_path, class: "nav-link"
    = yield

app/views/layouts/authentication.html.slim
doctype html
html
  head
    title Cheetah Ticket
    == stylesheet_link_tag "users", media: "all", "data-turbolinks-track" => true
    == csrf_meta_tags
  body
    .container
      .login
        .back-home
          = link_to "Back to Home page", root_path
        .tabs
          span
            = link_to "SIGN IN", login_path, class: ("inactive" unless controller_name == "sessions")
          span
            = link_to "SIGN UP", register_path, class: ("inactive" unless controller_name == "users")
        = yield

app/views/layouts/settings.html.slim
.container-fluid.no-pad.events-detail
  .row.no-pad
    .col-md-3.sidebar.settings-sidebar
      h3
        = fa_icon "cog"
        |  My Account
      ul
        li class=("active" if controller_name == "orders")
          = fa_icon "ticket"
          = link_to "Order Management", orders_path
        li class=("active" if controller_name == "events")
          = fa_icon "calendar"
          = link_to "Event Management", user_events_path(current_user)
    .col-md-9.tickets-buy.event-content.settings-content
      = yield :settings
= render template: "layouts/application"  